sudo: false
install:
  - "pip install ."
  - "pip install virtualenv"
  - "pip install coveralls"
script:
  - "make test"
after_success: "if [ $TRAVIS_OS_NAME == linux ] ; then coveralls ; fi"
matrix:
    include:
        - os: osx
          osx_image: xcode7.1
          language: generic
        - os: osx
          osx_image: xcode7.3
          language: generic
          env: BREW_PYTHON="python3"
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: pypy
        - os: linux
          python: pypy3
    allow_failures:
        - os: "osx"
