language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - "./g -s 0 -r -vvv"
after_success: coveralls
