sudo: false
install:
  - "pip install ."
  - "pip install virtualenv"
  - "pip install coveralls"
script:
  - "make test"
after_success: "if [ $TRAVIS_OS_NAME == linux ] ; then coveralls ; fi"
matrix:
    include:
        - os: osx
          osx_image: xcode7.1
          language: generic
          before_install:
              - brew update
              - brew install python
        - os: osx
          osx_image: xcode7.3
          language: generic
          before_install:
              - brew update
              - brew install python3
              - sudo rm /usr/bin/python2.7
              - ln -s /usr/local/bin/python3 /usr/local/bin/python
              - ln -s /usr/local/bin/pip3 /usr/local/bin/pip
        - os: osx
          osx_image: xcode7.3
          language: generic
          before_install:
              - brew update
              - brew install pypy
              - sudo rm /usr/bin/python2.7
              - which pypy
              - which pip_pypy
              - ln -s /usr/local/bin/pypy /usr/local/bin/python
              - ln -s /usr/local/bin/pip-pypy /usr/local/bin/pip
        - os: osx
          osx_image: xcode7.3
          language: generic
          before_install:
              - brew update
              - brew install pypy3
              - sudo rm /usr/bin/python2.7
              - which pypy3
              - which pip_pypy3
              - ln -s /usr/local/bin/pypy3 /usr/local/bin/python
              - ln -s /usr/local/bin/pip-pypy3 /usr/local/bin/pip
        - os: linux
          python: 2.7
          language: python
        - os: linux
          python: 3.4
          language: python
        - os: linux
          python: 3.5
          language: python
        - os: linux
          python: pypy
          language: python
        - os: linux
          python: pypy3
          language: python
