sudo: false
os:
  - "linux"
  - "osx"
language: "python"
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - "pip install ."
  - "pip install virtualenv"
  - "pip install coveralls"
script:
  - "make test"
after_success: "coveralls"
