sudo: false
install:
  - "pip install ."
  - "pip install virtualenv"
  - "pip install coveralls"
script:
  - "make test"
after_success: "if [ $TRAVIS_OS_NAME == linux ] ; then coveralls ; fi"
matrix:
    include:
        - os: osx
          osx_image: xcode7.1
          language: generic
          before_install:
              - brew update
              - sudo easy_install pip
        install:
          - "sudo pip install ."
          - "sudo pip install virtualenv"
          - "sudo pip install coveralls"
        - os: osx
          osx_image: xcode7.3
          language: generic
          before_install:
              - brew update
              - brew install python3
              - which python3
              - which pip3
        - os: osx
          osx_image: xcode7.3
          language: generic
          before_install:
              - brew update
              - brew install pypy
        - os: osx
          osx_image: xcode7.3
          language: generic
          before_install:
              - brew update
              - brew install pypy3
        - os: linux
          python: 2.7
          language: python
        - os: linux
          python: 3.4
          language: python
        - os: linux
          python: 3.5
          language: python
        - os: linux
          python: pypy
          language: python
        - os: linux
          python: pypy3
          language: python
