version: "{build}"
build: false
environment:
    matrix:
        - PYTHON: "C:/Python27"
init:
    - "ECHO %PYTHON%"
    - ps: "ls C:/Python*"
install:
      - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
      - "%PYTHON%/python.exe C:/get-pip.py"
      - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
test_script:
    - "%PYTHON%/python.exe -m green.cmdline -vvv -t green"
    - "%PYTHON%/python.exe -m green.cmdline -vvv -W green"
platform:
    - AnyCPU
